# Generated by Django 4.2.30 on 2026-08-12 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('APPROVAL', 'Approval'), ('ACCOUNT', 'Account'), ('IMPORT', 'Import'), ('COMMS', 'Communications'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('ACTION', 'Action required'), ('WARNING', 'Warning')], default='INFO', max_length=10)),
                ('default_channels', models.JSONField(default=list)),
                ('audience_rule', models.JSONField(default=dict)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_NotificationType',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('INAPP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='INAPP', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_NotificationPreference',
                'unique_together': {('user', 'type_code', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('APPROVAL', 'Approval'), ('ACCOUNT', 'Account'), ('IMPORT', 'Import'), ('COMMS', 'Communications'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('ACTION', 'Action required'), ('WARNING', 'Warning')], default='INFO', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('target_route', models.CharField(blank=True, default='', max_length=255)),
                ('source_ref', models.CharField(blank=True, default='', max_length=255)),
                ('group_key', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationtype')),
            ],
            options={
                'db_table': 'notifications_Notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_badge_idx'), models.Index(fields=['source_ref'], name='notif_source_idx'), models.Index(fields=['recipient', 'group_key'], name='notif_group_idx')],
            },
        ),
    ]
